apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: default
#common configuration shared between all applications
data:
  application.yml: |-
    configserver:
      name:  JHipster Registry
      status: Connected to the JHipster Registry running in Kubernetes
    eureka:
      client:
        initial-instance-info-replication-interval-seconds: 30
        instance-info-replication-interval-seconds: 30
        registry-fetch-interval-seconds: 30
        fetch-registry: true
        register-with-eureka: true
        eureka-service-url-poll-interval-seconds: 30
      instance:
        lease-renewal-interval-in-seconds: 30
        registry-default-open-for-traffic-count: 0
    jhipster:
      security:
        authentication:
          jwt:
            base64-secret: MDhkNGNlYjBmNWZhNWY4OGVkNDNiOTc1NmFiNGMyNmRhYzRkNzQ0MGI0MzQ0MWEwOGQ1MzFiM2FkMGFkNDIxNDgyNjIzNjliYTZkMjVlYWEzNDEyODc3MWYxZTlkNWY3NTRkZg==
  # app specific configuration
  jhipster-registry.yml: |-
    eureka:
      client:
        service-url:
          defaultZone: http://admin:${spring.security.user.password}@jhipster-registry-0.jhipster-registry.default.svc.cluster.local:8761/eureka/,http://admin:${spring.security.user.password}@jhipster-registry-1.jhipster-registry.default.svc.cluster.local:8761/eureka/
