apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-app
  namespace: fairenough
  labels:
    team: fairenough
spec:
  selector:
    matchLabels:
      app: gateway
  endpoints:
    - port: web
      path: /prometheusMetrics
