apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      version: 'v1'
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: gateway
        version: 'v1'
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - gateway
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: gateway-app
          image: kidscare8playground/gateway
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://admin:${jhipster.registry.password}@jhipster-registry.default.svc.cluster.local:8761/config
            - name: JHIPSTER_REGISTRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: registry-secret
                  key: registry-admin-password
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://admin:${jhipster.registry.password}@jhipster-registry.default.svc.cluster.local:8761/eureka/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://acid-fairenough.default.svc.cluster.local:5432/gateway
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gateway.acid-fairenough.credentials.postgresql.acid.zalan.do
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gateway.acid-fairenough.credentials.postgresql.acid.zalan.do
                  key: password      
            - name: SPRING_DATASOURCE_READ_SLAVE_URL
              value: jdbc:postgresql://acid-fairenough-repl.default.svc.cluster.local:5432/gateway
            - name: SPRING_DATASOURCE_READ_SLAVE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gateway.acid-fairenough.credentials.postgresql.acid.zalan.do
                  key: username
            - name: SPRING_DATASOURCE_READ_SLAVE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gateway.acid-fairenough.credentials.postgresql.acid.zalan.do
                  key: password
            - name: SPRING_DATASOURCE_READ_SLAVE_ENABLED
              value: 'true'
            - name: JHIPSTER_METRICS_LOGS_ENABLED
              value: 'true'
            - name: JHIPSTER_LOGGING_LOGSTASH_ENABLED
              value: 'true'
            - name: JHIPSTER_LOGGING_LOGSTASH_HOST
              value: jhipster-logstash
            - name: SPRING_ZIPKIN_ENABLED
              value: 'true'
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://jhipster-zipkin
            - name: SPRING_SLEUTH_PROPAGATION_KEYS
              value: 'x-request-id,x-ot-span-context'
            - name: JAVA_OPTS
              value: ' -Xmx256m -Xms256m'
          resources:
            requests:
              memory: '384Mi'
              cpu: '100m'
            limits:
              memory: '1Gi'
              cpu: '1'
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /management/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /management/health
              port: http
            initialDelaySeconds: 120
