commonLabels:
  app.kubernetes.io/genereted-by: JHipster

namespace: fairenough

resources:
  - namespace.yml
  # Individual apps
  - gateway-k8s/gateway-deployment.yml
  - gateway-k8s/gateway-service.yml
  - gateway-k8s/gateway-mysql.yml
  - gateway-k8s/gateway-prometheus-sm.yml
  # monitoring prometheus
  - monitoring-k8s/jhipster-prometheus-cr.yml
  - monitoring-k8s/jhipster-prometheus-crd.yml
  - monitoring-k8s/jhipster-grafana.yml
  - monitoring-k8s/jhipster-grafana-dashboard.yml
  # service discovery eureka/consul
  - registry-k8s/jhipster-registry.yml
  - registry-k8s/application-configmap.yml

patchesJson6902:
