apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurations
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configurations
      version: "v1"
  template:
    metadata:
      labels:
        app: configurations
        version: "v1"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - configurations
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: configurations-app
          image: kidscare8playground/configurations
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://admin:${jhipster.registry.password}@jhipster-registry.default.svc.cluster.local:8761/config
            - name: JHIPSTER_REGISTRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: registry-secret
                  key: registry-admin-password
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://admin:${jhipster.registry.password}@jhipster-registry.default.svc.cluster.local:8761/eureka/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://acid-fairenough.postgres-cluster.svc.cluster.local:5432/configurations
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: configurations.acid-fairenough.credentials.postgresql.acid.zalan.do.postgres-cluster
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: configurations.acid-fairenough.credentials.postgresql.acid.zalan.do.postgres-cluster
                  key: password
            - name: SPRING_DATASOURCE_READ_SLAVE_URL
              value: jdbc:postgresql://acid-fairenough-repl.postgres-cluster.svc.cluster.local:5432/configurations
            - name: SPRING_DATASOURCE_READ_SLAVE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: configurations.acid-fairenough.credentials.postgresql.acid.zalan.do.postgres-cluster
                  key: username
            - name: SPRING_DATASOURCE_READ_SLAVE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: configurations.acid-fairenough.credentials.postgresql.acid.zalan.do.postgres-cluster
                  key: password
            - name: SPRING_DATASOURCE_READ_SLAVE_ENABLED
              value: 'true'
            - name: SPRING_LIQUIBASE_URL
              value: jdbc:postgresql://acid-fairenough.postgres-cluster.svc.cluster.local:5432/configurations
            - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
              value: "true"
            - name: SPRING_SLEUTH_PROPAGATION_KEYS
              value: "x-request-id,x-ot-span-context"
            - name: JAVA_OPTS
              value: " -Xmx256m -Xms256m"
            - name: SERVER_SHUTDOWN
              value: graceful
          resources:
            requests:
              memory: "384Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - name: http
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: http
            initialDelaySeconds: 120
