apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: configurations-app
  namespace: default
  labels:
    team: default
spec:
  selector:
    matchLabels:
      app: configurations
  endpoints:
    - targetPort: 8081
      path: /management/prometheus
